### ISSUE TITLE
\PDFcontainer corrupted with LaTeX kernel 2019-10-01

### ISSUE THREAD

**Issue by mrpiggi** [rolfn/pst-pdf#1]
With the latest LaTeX kernel, the package `pst-pdf` includes not only content related to `pstricks` but every graphic given with `\includegraphics` within `\PDFcontainer`. See the MWE below.

```tex
%\RequirePackage[2018/12/01]{latexrelease}
\documentclass{article}
\usepackage{mwe}
\usepackage{pst-pdf}
\begin{document}
\includegraphics{example-image}

\begin{pspicture}(-5.5,-5.25)(5.25,5.25)% 
  \pscircle*[linecolor=red]{5}
  \Huge\sffamily\bfseries
  \rput(-4.5,4.5){A} \rput(4.5,4.5){B}
  \rput(-4.5,-4.5){C}\rput(4.5,-4.5){D}
  \rmfamily
  \rput(0,-3.8){PSTricks}
  \rput(0,3.8){\LaTeX}
\end{pspicture}
\end{document}
```

**Comment by hvoss49** [comment]
This will work and will be part of the next update of `pst-pdf`

```
\documentclass{article}
\usepackage{pst-pdf}
\makeatletter
\renewcommand*\ppf@is@pdfTeX@graphic[5]{%
  \@ppf@pdftex@graphicfalse%
  \begingroup
    \edef\pdfTeXext{\detokenize\expandafter{#2}}%<----added
    \def\Gin@setfile##1##2##3{%
      \edef\@tempb{\detokenize\expandafter{##2}}%
      \@for\@tempa:=\pdfTeXext\do{%
        \ifx\@tempa\@tempb\global\@ppf@pdftex@graphictrue\fi}}%
    \edef\Gin@extensions{#2,#3}%
    \pr@outerfalse\ppf@Ginclude@graphics{#1}%
  \endgroup
  \if@ppf@pdftex@graphic#4\else#5\fi
}
\makeatother

\begin{document}
\includegraphics{example-image}
\begin{pspicture}[showgrid](5,5)
\end{pspicture}
\end{document}
```

**Comment by mrpiggi** [comment]
Just for completeness, this issue was discussed here: latex3/latex2e#196

**Comment by mrpiggi** [comment]
In addition, maybe it would be possible to change the redefinition of `\makeindex` during the extraction mode in order to consider packages like `imakeidx` or `indextools` which define an additional optional argument. So, instead of doing `\let\makeindex\@empty` I would suggest to do
```tex
\renewcommand*\makeindex[1][]{}
\renewcommand*\printindex[1][]{}
```

**Comment by davidcarlisle** [comment]
@hvoss49  sorry about that I'd have given you advance notice if I had spotted that, it's hard to check everything though.

**Comment by rolfn** [comment]
@mrpiggi Many thanks for preparing your merge request. All seems to be correct now. I will put a new version to CTAN soon.
