### ISSUE TITLE
pst-pdf loads pdftex.def in dvi mode 

### ISSUE THREAD

**Issue by u-fischer** [rolfn/pst-pdf#5]
pst-pdf loads pdftex.def in dvi mode probably with the goal to get the list of graphics extensions:

~~~~
%line 113 of pst-pdf.sty
  \begingroup
    \let\AtBeginDocument\@gobble \let\PackageWarningNoLine\@gobbletwo
    \chardef\pdftexversion=121 %
    \newcount\pdfoutput
    \pdfoutput=1 %
    \input{pdftex.def}%
    \edef\x{\endgroup\def\noexpand\ppf@other@extensions{\Gin@extensions}
    }%
  \x
~~~~

This worked until now, but fails with the newest pdftex.def as it stores globally code for a better page color handling in a kernel hook and this errors if the code is executed in dvi mode:

~~~~
% compile with latex
\documentclass{article}
\usepackage{graphicx}
\usepackage{pst-pdf}
\AddToHook{shipout/background}{\relax}
\begin{document}
Hello World...
\includegraphics{example-image.eps}
\end{document}
~~~~

gives 

~~~~
! Undefined control sequence.
\@kernel@before@shipout@background ...T@pagecolor 
                                                  \put (-\hoffset ,-\pdfpage...
l.28 \includegraphics{example-image.eps}
~~~~

It would be perhaps possible (but not completly trivial) to protect this code to be executed in dvi-mode, but imho it would be better if pst-pdf wouldn't load a file meant for pdf mode in dvi mode. Could pst-pdf avoid to do this?

**Comment by rolfn** [comment]
You're right! Loading `pdftex.def`  is too complicated to just get the graphic endings. I now define these endings explicitly. A new version is on the way to CTAN.Thanks for the bug report.

**Comment by u-fischer** [comment]
Thanks!
