### ISSUE TITLE
Interaction with hyperref/preview

### ISSUE THREAD

**Issue by mrpiggi** [rolfn/pst-pdf#6]
For some time now, it has unfortunately been the rule rather than the exception that changes to the LaTeX kernel break well-known and frequently used packages. One of the most recent changes concerns the package `preview', which was released with 2010-10-01. tex.stackexchange.com/questions/587774 gives a overview, who was already informed about this issue.

So currently it is not possible to use `pst-pdf` together with `hyperref` due to bug respectively missing adaptions of `preview` and as this probably will not be fixed (https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44578) it might be appropriate to figure an alternative approach...
```latex
\documentclass{article}
\usepackage{pst-pdf}
\usepackage{hyperref}
\begin{document}
\noindent
\begin{pspicture}(10,2)
\psframe(0,0)(10,2)
\end{pspicture}
\end{document}
```

**Comment by rolfn** [comment]
I can confirm the problem. If I add the following code as Ulrike suggested, ghostscript no longer shows any errors:
```latex
\documentclass{article}
\usepackage{pst-pdf}
\usepackage{hyperref}

\makeatletter
 \let\Hy@FirstPageHook\relax
 \let\Hy@EveryPageAnchor\relax
\makeatother

\begin{document}
\noindent
\begin{pspicture}(10,2)
\psframe(0,0)(10,2)
\end{pspicture}
\end{document}
```
Would the permanent insertion in `pst-pdf` be a solution? What do you think?

My environment:
* latex --version `--> pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)`
* hyperref.sty `--> 2021-02-27 v7.00k`
* pst-pdf.sty `--> 2020/10/10 v1.2f`
* dvips --version `--> This is dvips(k) 2021.1`
* gs --version `--> 9.52`

**Comment by mrpiggi** [comment]
As @u-fischer already mentioned, this is just a workaround and nothing what should be permanently added. So either package `preview` is adopted to the current kernel changes or a solution without `preview` at all is needed.

**Comment by u-fischer** [comment]
Well if doesn't hurt to include my fix (but naturally inside a `\ifPreview ... \fi`), but it won't fix everything. Other packages can/will add code to the LaTeX-shipout hooks too, and then preview can break again.

**Comment by rolfn** [comment]
It is a problem of "preview". "preview" is essential for "pst-pdf". I can not do anything.

**Comment by 1a7r0ch3** [comment]
For the time being, if anyone needs pst-pdf with beamer, see yet another workaround given by Ulrike Fischer https://tex.stackexchange.com/q/617229/70966 .

**Comment by rolfn** [comment]
You may also be interested in another development: https://github.com/zauguin/luapstricks

With an up-to-date PSTricks installation, almost all PSTricks documents will work if you are using LuaLaTeX. This is a much better way than `pst-pdf`!

**Comment by mrpiggi** [comment]
In the meantime, I came up with a automated solution by disabling `hyperref` for the auxiliary run in DVI mode as well as calling `auto-pst-pdf` only if necessary. This could be of course tweaked but I will leave it here as it is.
```latex
\documentclass{article}
\usepackage{iftex}
\usepackage{pdftexcmds}
\usepackage{pstricks}

\makeatletter
\ifpdf
  \def\@tempa{off}
  \ifnum\pdf@shellescape=\@ne\relax
    \ifnum\pdf@strcmp
          {\pdf@filemoddate{\jobname.tex}}
          {\pdf@filemoddate{\jobname-pics.pdf}}
        >0 \relax
      \def\@tempa{on}
    \fi
  \fi
  \PassOptionsToPackage{\@tempa}{auto-pst-pdf}
\else
  \disable@package@load{hyperref}{}
  \disable@package@load{bookmark}{}
  % maybe provide stubs for used hyperref commands
  % \providerobustcmd*\href[3][]{#3}
  % \providecommand*\hyperpage[1]{#1}
\fi
\makeatother

\usepackage{auto-pst-pdf}
\usepackage{hyperref}
\begin{document}
test
\begin{pspicture}(5,1)
\psframe(5,1)
\end{pspicture}
test
\end{document}
```
Edit: As `hyperref` is not loaded at all with this approach during the processing with `latex`, all of it's commands used have to be provided as least as stubbed commands.

**Comment by rolfn** [comment]
Please note that I can't comment on `auto-pst-pdf` and I don't have time to improve `pst-pdf` either. 

Otherwise I believe that in most cases compiling PSTricks documents is possible in a better way with LuaLaTeX.

**Comment by mrpiggi** [comment]
Totally fine. I just wanted to present a suitable solution for someone who happens to stumble across this problem here.
